# fly.toml app configuration file generated for commitlog on 2025-10-02T10:39:57+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'commitlog'
primary_region = 'nrt'

[build]
  dockerfile = 'Dockerfile'

[env]
  DATABASE_PATH = '/data/commitlog.db'
  GIN_MODE = 'release'
  PORT = '8080'
  UPLOAD_DIR = '/data/uploads'
  UPLOAD_URL_PATH = '/uploads'

[[mounts]]
  source = 'commitlog_data'
  destination = '/data'
  initial_size = '1GB'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1

[checks]
  [checks.healthz]
    port = 8080
    type = 'http'
    interval = '10s'
    timeout = '2s'
    grace_period = '20s'
    method = 'GET'
    path = '/healthz'

[[vm]]
  memory_mb = 256
  cpu_kind = 'shared'
  cpus = 1
