app = "commitlog"
primary_region = "nrt"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  DATABASE_PATH = "/data/commitlog.db"
  GIN_MODE = "release"

[[mounts]]
  source = "commitlog_data"
  destination = "/data"
  initial_size = "1GB"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = "true"
  min_machines_running = 1

[checks]
  [checks.healthz]
    type = "http"
    port = 8080
    interval = "10s"
    timeout = "2s"
    grace_period = "20s"
    method = "GET"
    path = "/healthz"

# 机密信息：使用 `fly secrets set SESSION_SECRET=...` 设置 Cookie 加密密钥。
